const ALLOWED_TRANSITIONS = Object.freeze({ REVISAO_JURIDICA: ['PETICIONAMENTO','INVESTIGACAO_AGENCIA'], INVESTIGACAO_AGENCIA: ['INVESTIGACAO_RETAGUARDA','MONITORAMENTO'], INVESTIGACAO_RETAGUARDA: ['PETICIONAMENTO','MONITORAMENTO'], PETICIONAMENTO: ['AGUARDANDO_RESULTADO'], AGUARDANDO_RESULTADO: ['MONITORAMENTO'] });
function canTransition(from, to) { return (ALLOWED_TRANSITIONS[from] || []).includes(to); }
module.exports = { ALLOWED_TRANSITIONS, canTransition };
